 USE [master]
GO
/****** Object:  Database [ClearViewService]    Script Date: 08/04/2009 14:36:41 ******/
CREATE DATABASE [ClearViewService] ON  PRIMARY 
( NAME = N'ClearViewService', FILENAME = N'F:\Production\Database\ClearViewService.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ClearViewService_log', FILENAME = N'G:\Production\Logs\ClearViewService_log.ldf' , SIZE = 312768KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
EXEC dbo.sp_dbcmptlevel @dbname=N'ClearViewService', @new_cmptlevel=90
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ClearViewService].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO
ALTER DATABASE [ClearViewService] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ClearViewService] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ClearViewService] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ClearViewService] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ClearViewService] SET ARITHABORT OFF 
GO
ALTER DATABASE [ClearViewService] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ClearViewService] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [ClearViewService] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ClearViewService] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ClearViewService] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ClearViewService] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ClearViewService] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ClearViewService] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ClearViewService] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ClearViewService] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ClearViewService] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ClearViewService] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ClearViewService] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ClearViewService] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ClearViewService] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ClearViewService] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ClearViewService] SET  READ_WRITE 
GO
ALTER DATABASE [ClearViewService] SET RECOVERY FULL 
GO
ALTER DATABASE [ClearViewService] SET  MULTI_USER 
GO
ALTER DATABASE [ClearViewService] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ClearViewService] SET DB_CHAINING OFF 