USE [master]
GO
/****** Object:  Database [ClearViewAsset]    Script Date: 08/04/2009 14:33:23 ******/
CREATE DATABASE [ClearViewAsset] ON  PRIMARY 
( NAME = N'ClearViewAsset', FILENAME = N'F:\Production\Database\ClearViewAsset.mdf' , SIZE = 11264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ClearViewAsset_log', FILENAME = N'G:\Production\Logs\ClearViewAsset_log.ldf' , SIZE = 104704KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
EXEC dbo.sp_dbcmptlevel @dbname=N'ClearViewAsset', @new_cmptlevel=90
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ClearViewAsset].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO
ALTER DATABASE [ClearViewAsset] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ClearViewAsset] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ClearViewAsset] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ClearViewAsset] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ClearViewAsset] SET ARITHABORT OFF 
GO
ALTER DATABASE [ClearViewAsset] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ClearViewAsset] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [ClearViewAsset] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ClearViewAsset] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ClearViewAsset] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ClearViewAsset] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ClearViewAsset] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ClearViewAsset] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ClearViewAsset] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ClearViewAsset] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ClearViewAsset] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ClearViewAsset] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ClearViewAsset] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ClearViewAsset] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ClearViewAsset] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ClearViewAsset] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ClearViewAsset] SET  READ_WRITE 
GO
ALTER DATABASE [ClearViewAsset] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [ClearViewAsset] SET  MULTI_USER 
GO
ALTER DATABASE [ClearViewAsset] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ClearViewAsset] SET DB_CHAINING OFF  