USE [master]
GO
/****** Object:  Database [Clearview]    Script Date: 08/04/2009 14:31:31 ******/
CREATE DATABASE [Clearview] ON  PRIMARY 
( NAME = N'Clearview', FILENAME = N'F:\Production\Database\Clearview.mdf' , SIZE = 178176KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Clearview_log', FILENAME = N'G:\Production\Logs\Clearview_log.ldf' , SIZE = 104704KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
EXEC dbo.sp_dbcmptlevel @dbname=N'Clearview', @new_cmptlevel=90
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Clearview].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO
ALTER DATABASE [Clearview] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Clearview] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Clearview] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Clearview] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Clearview] SET ARITHABORT OFF 
GO
ALTER DATABASE [Clearview] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Clearview] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [Clearview] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Clearview] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Clearview] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Clearview] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Clearview] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Clearview] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Clearview] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Clearview] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Clearview] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Clearview] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Clearview] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Clearview] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Clearview] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Clearview] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Clearview] SET  READ_WRITE 
GO
ALTER DATABASE [Clearview] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Clearview] SET  MULTI_USER 
GO
ALTER DATABASE [Clearview] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Clearview] SET DB_CHAINING OFF  